services:
  apache:
    build:
      context: ./ingress
    container_name: ctf-apache
    environment:
      SSH_PIVOT_PASSWORD: ${SSH_PIVOT_PASSWORD}
    ports:
      - "8080:80"
      - "2222:22"
    networks:
      - public_net
      - internal_net
    depends_on:
      - web-gateway
      - frontend
    volumes:
      - type: bind
        source: ./flags/final_flag.txt
        target: /root/final_flag.txt
        read_only: true

  postgres:
    build: ./datastores/postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./datastores/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    networks:
      - internal_net

  web-gateway:
    build: ./web-gateway
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CERTIFICATE_DIR: /certificates
      FLAG_STAGE2: ${FLAG_STAGE2}
      FLAG_STAGE3: ${FLAG_STAGE3}
    volumes:
      - certificates:/certificates
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal_net
      - public_net

  frontend:
    build: ./frontend
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    networks:
      - public_net
    depends_on:
      - web-gateway

  celery-worker:
    build: ./celery-worker
    restart: unless-stopped
    command: celery -A celery_app worker --loglevel=INFO
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SSH_PIVOT_PASSWORD: ${SSH_PIVOT_PASSWORD}
      CERTIFICATE_DIR: /certificates
    depends_on:
      - redis
      - postgres
    volumes:
      - certificates:/certificates
      - type: bind
        source: ./flags/user_flag.txt
        target: /flags/user_flag.txt
        read_only: true
      - type: bind
        source: ./flags/root_flag.txt
        target: /root/.root_flag_seed
        read_only: true
    networks:
      - internal_net

networks:
  public_net:
    driver: bridge
  internal_net:
    internal: true

volumes:
  pgdata:
  certificates:
